### ISSUE TITLE
see if we can improve the documentation associated with the user and group tests in the windows schema

### ISSUE THREAD

**Issue by djhaynes** [OVALProject/Language#101]
Please see the following oval-developer-list post for additional information.

http://making-security-measurable.1364806.n2.nabble.com/Question-about-the-intended-behavior-of-Windows-User-and-Group-objects-td6717805.html#a6721806

**Comment by solind** [comment]
Since my original inquiries, the behavior of the OVAL language seems to have become standardized (via the NIST validation program) as follows:

Use the Windows SDK LookupAccountName or LookupAccoundSid functions to get domain and username strings.

- Members of the "BUILTIN" and "NT AUTHORITY" domains are considered built-in users, and the domain names are not shown in username item entities.
- Local Administrator and Guest accounts are also considered built-in users (domain not shown in username item entities), provided they have the username "Administrator" and "Guest", and the SIDs [Computer SID]-500 and [Computer SID]-501, respectively.
- Every other user, including an NT Service account, is represented using a Netbios name, i.e., the format DOMAIN\Username.

I'll update the schema documentation to reflect this.
