### ISSUE TITLE
discuss and document not collected item entities versus not collecting item entities

### ISSUE THREAD

**Issue by djhaynes** [OVALProject/Language#105]
We need to discuss and document not collected item entities (i.e. item entities
with a status='not collected') versus not collecting item entities (i.e. item
entities that are not reported in the item).

**Comment by solind** [comment]
Documented in 5.3.4.1.4 of the 5.11.2 update to the OVAL Language specification.

**Comment by dragosprisaca** [comment]
Since the section id (5.3.4.1.4) has changed, I want to reference the section name: "Determining the Final Result of an OVAL State Entity Evaluation" which includes the fix.

**Comment by solind** [comment]
Hi Dragos, from where would you like this referenced?  The language specification seemed like the appropriate place.  Here's how it reads:

> 5.3.4.1.4	entity_check Evaluation
An OVAL Item may contain multiple occurrences of an OVAL Item Entity to represent that the OVAL Item has multiple values for that particular OVAL Item Entity. The entity_check property specifies how many occurrences of an OVAL Item Entity MUST match the OVAL State Entity, as defined in Section 5.3.4.1 OVAL State Entity Evaluation, in order to evaluate to ‘true’. The valid values for the entity_check property are defined by the CheckEnumeration. See Section 5.3.6.1 Check Enumeration Evaluation for more information about how to apply the property.

**Comment by dragosprisaca** [comment]
In OVAL 5.11.1 specification, the section 5.3.4.1.4 points to "Determining the Final Result of an OVAL State Entity Evaluation", but in 5.11.2 (I think there was a new section added) it points to "5.3.4.1.4 entity_check Evaluation". 

You said, the fix was "Documented in 5.3.4.1.4 ...", but I think it should have been "5.3.4.1.5 "Determining the Final Result of an OVAL State Entity Evaluation""

**Comment by solind** [comment]
Yes, I inserted a new section 5.3.4.1.4, and the old 5.3.4.1.4 became 5.3.4.1.5.  I felt that entity_check had to be documented before the "Final Result" determination could be documented.

A new section on the entity_check in the context of a state entity evaluation became necessary because we added it to state entities in 5.11, but the specification had never been updated to reflect this fact.  I added that section, and I intentionally referenced it above.

So, to summarize, the addition of the entity_check to state entities in 5.11 had already resolved this issue.  But since the specification had no documentation about it, I added a note to the effect that the documentation would be added for the OVAL 5.11.2 release.

The new 5.3.4.1.5 reads:

> 5.3.4.1.5	Determining the Final Result of an OVAL State Entity Evaluation
The final result of an OVAL State Entity Evaluation is determined by first evaluating the check_existence property of the OVAL State Entity with respect to corresponding OVAL Item Entities.  If the result of the existence test is true, the value specified in the OVAL State Entity is then compared with each occurrence of a corresponding OVAL Item Entity, in the context of the specified datatype and operation as defined in Section 5.3.3.3.1 Datatype and Operation Evaluation. If any OVAL Item Entity xsi:nil attribute is set to true, the result of its comparison with a corresponding OVAL State Entity should be “not evaluated”. In the event that there is no corresponding entity appearing in the OVAL Item, it is equivalent to there being a single corresponding entity with a status property value of “not collected” (i.e., evaluation proceeds as though the item entity was not collected; non-existent OVAL Item entities should appear with a status property value of “does not exist”).
The results of the comparisons are evaluated against the specified entity_check property according to Section 5.3.6.1 Check Enumeration Evaluation. This will be the final result of the OVAL State Entity Evaluation unless an OVAL Variable was also referenced.
If an OVAL Variable was referenced, the above procedure must be performed for each value in the OVAL Variable, then the final result must be computed by examining the var_check property and the individual results for each OVAL Variable value comparison.  See Section 5.3.6.4 Variable Check Evaluation.

**Comment by wmunyan** [comment]
This is a similar question to the issue around the reg_multi_sz discussion.  What if the expected state of an element is that xsi:nil="true"?  i.e. an assessment is specifically checking for a null value.  If the OVAL Item Entity was collected as xsi:nil="true", and that's what's expected, the always "not evaluated" result wouldn't be correct.  Might be an edge case, but I thought I'd ask now that it's the 11th hour :)

**Comment by solind** [comment]
Hmm.  Good point...

**Comment by solind** [comment]
The only nillable state entity I've found in the OVAL language is the apache-def:httpd_state/binary_name entity.  Hopefully that means we can safely ignore this edge case! :)
