### ISSUE TITLE
Document how bitwise ops work on integers

### ISSUE THREAD

**Issue by chisholm** [OVALProject/Language#171]
We need to document how OVAL int values convert to and from a "virtual" binary representation which binary ops operate on.  This applies to the bitwise int operation descriptions given in section 5.3.6.3.1 of the spec, and to the binary function proposal which is currently in the sandbox.

**Comment by solind** [comment]
Actually the binary representations do not matter, provided that they are identical for both integers being compared.

The real issue is how to interpret negative numbers.  It seems the normal convention is to use the most significant bit to represent the sign.  When two numbers are compared, the sign bit should be padded to align with the sign bit of the largest number.
