### ISSUE TITLE
 add support for a macos-def:diskutil_test

### ISSUE THREAD

**Issue by chisholm** [OVALProject/Language#197]
Please see the following link for more information.

http://making-security-measurable.1364806.n2.nabble.com/A-couple-of-tests-of-OS-X-tp5369043.html

(copied from internal language issue #27331)
(also corresponds to interpreter feature request [#114](http://sourceforge.net/p/ovaldi/feature-requests/114/))

**Comment by solind** [comment]
See also Issue #109.

**Comment by solind** [comment]
The intention behind this test appeared to me to be to check whether permissions were less restrictive than designed (i.e., installed).  Since the diskutil verifyPermissions (and its successor in MacOS X 10.11, repair_packages --verify) show all files with permissions and ownerships that have changed since installed, that seems perfectly sufficient to meeting the intended purpose of the test.

So, if you wanted to check that the permissions are at least as strict as they were at install-time using the diskutil_test as it's currently designed, you'd write a test with a @check_existence of "any_exist" (permitting unchanged files which would not appear in the output), and if there are existing matches, insure a PermissionCompareType of LESS or SAME.

Outright permission checks irrespective of install-time can also still be written using the unix:file_test.
