### ISSUE TITLE
further specify how to evaluate deprecated constructs

### ISSUE THREAD

**Issue by djhaynes** [OVALProject/Language#7]
Right now, we document how to evaluate deprecated definitions.  However, we do
not specify how to evaluate deprecated tests, objects, and states.

Tests, objects, and states should be evaluated in the same manner as when they
were not deprecated.  It is just that their use is strongly discouraged.  We need to include this information in the specification.

**Comment by solind** [comment]
Use of the deprecated value should imply that the content was authored in the context of OVAL version 5.3.  For instance, if OVAL 5.3 content were to be upgraded so that it could be included with later-version OVAL content, a @check_existence attribute would be created that has a default value, but no meaning intended by the author.
